version: '3.2'

services:

  loot:

    network_mode: "host"

    image: goloot

    build:
      context: .
      dockerfile: Dockerfile

    container_name: loot2

    volumes:
      - type: bind
        source: /var/www/goloot
        target: /src/app

    command: ./runner

